spring.application.name=demo

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/backend_db
spring.datasource.username=postgres
spring.datasource.password=834001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Redis
spring.redis.host=localhost
spring.redis.port=6379
